<?php
	declare(strict_types=1);
	/** @var ImageProxyExtension $this */
?>
<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())) ?>" method="post">
	<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
	<div class="form-group">
		<label class="group-name" for="allow_url"><?= _t('ext.replaceEntryUrl.allow_url') ?></label>
		<div class="group-controls">
			<input type="text" name="allow_url" id="allow_url"
				value="<?= htmlspecialchars(FreshRSS_Context::userConf()->attributeString('allow_url') ?? '', ENT_COMPAT, 'UTF-8') ?>">
		</div>
	</div>


	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
			<button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
		</div>
	</div>
</form>
