<?php
declare(strict_types=1);
/** @var ReadingTimeExtension $this */
?>
<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="reading_time_speed"><?php echo _t('ext.reading_time.speed.label'); ?></label>
		<div class="group-controls">
			<input type="number" id="reading_time_speed" name="reading_time_speed" value="<?= $this->getSpeed() ?>" min="1">
			<p class="help"><?= _i('help') ?> <?= _t('ext.reading_time.speed.help') ?></p>
		</div>

		<label class="group-name" for="reading_time_speed"><?php echo _t('ext.reading_time.metrics.label'); ?></label>
		<div class="group-controls">
			<select name="reading_time_metrics" id="reading_time_metrics" data-leave-validation="<?= $this->getMetrics() ?>">
				<option value="words"<?= $this->getMetrics() === 'words' ? ' selected="selected"' : '' ?>><?= _t('ext.reading_time.metrics.words') ?></option>
				<option value="letters"<?= $this->getMetrics() === 'letters' ? ' selected="selected"' : '' ?>><?= _t('ext.reading_time.metrics.letters') ?></option>
			</select>
			<p class="help"><?= _i('help') ?> <?= _t('ext.reading_time.metrics.help') ?></p>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>
