<?php
declare(strict_types=1);
/** @var CaptchaExtension $this */

if (!Minz_ExtensionManager::isExtensionEnabled($this->getName())) {
	echo '<br /><b>' . _t('ext.form_captcha.ext_must_be_enabled') . '</b>';
	return;
}

$config = CaptchaExtension::getConfig();
?>
<form
	action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())) ?>"
	method="post"
	autocomplete="off"
	spellcheck="false"
	data-auto-leave-validation="1">

	<input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />

	<div class="form-group">
		<label class="group-name"><?= _t('ext.form_captcha.protected_pages') ?></label>
		<div class="group-controls">
			<div class="stick">
				<?php # `auth_register` also protects `user_create` ?>
				<input type="checkbox" name="protectedPages[]" value="auth_register"<?= in_array('auth_register', $config['protectedPages'], true) ? 'checked="checked"' : '' ?> />
				<label for="protectedPages[]"><?= _t('ext.form_captcha.pages.register') ?></label>
			</div>
			<br />
			<div class="stick">
				<input type="checkbox" name="protectedPages[]" value="auth_formLogin"<?= in_array('auth_formLogin', $config['protectedPages'], true) ? 'checked="checked"' : '' ?> />
				<label for="protectedPages[]"><?= _t('ext.form_captcha.pages.login') ?></label>
			</div>
		</div>
	</div>

	<div class="form-group">
		<label class="group-name" for="captchaProvider"><?= _t('ext.form_captcha.captcha_provider') ?></label>
		<div class="group-controls">
			<select id="captchaProvider" name="captchaProvider">
				<option value="none"<?= $config['captchaProvider'] === 'none' ? ' selected="selected"' : '' ?>><?= _t('ext.form_captcha.providers.none') ?></option>
				<option value="turnstile"<?= $config['captchaProvider'] === 'turnstile' ? ' selected="selected"' : '' ?>>Cloudflare Turnstile</option>
				<option value="recaptcha-v2"<?= $config['captchaProvider'] === 'recaptcha-v2' ? ' selected="selected"' : '' ?>>reCAPTCHA v2</option>
				<option value="recaptcha-v3"<?= $config['captchaProvider'] === 'recaptcha-v3' ? ' selected="selected"' : '' ?>>reCAPTCHA v3</option>
				<option value="hcaptcha"<?= $config['captchaProvider'] === 'hcaptcha' ? ' selected="selected"' : '' ?>>hCaptcha</option>
			</select>
		</div>
	</div>

	<template class="captchaTmpl" id="common">
		<div class="form-group">
			<label class="group-name" for="provider[siteKey]"><?= _t('ext.form_captcha.providers.site_key.label') ?></label>
			<div class="group-controls">
				<input type="text" name="provider[siteKey]" placeholder="<?= _t('ext.form_captcha.providers.site_key.placeholder') ?>" value="<?= $config['provider']['siteKey'] ?? '' ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="provider[secretKey]"><?= _t('ext.form_captcha.providers.secret_key.label') ?></label>
			<div class="group-controls">
				<div class="stick">
					<input type="password" name="provider[secretKey]" placeholder="<?= _t('ext.form_captcha.providers.secret_key.placeholder') ?>" value="<?= $config['provider']['secretKey'] ?? '' ?>" />
					<button type="button" class="btn toggle-password"><?= _i('key') ?></button>
				</div>
			</div>
		</div>

		<div class="form-group">
			<label class="group-name" for="sendClientIp"><?= _t('ext.form_captcha.send_client_ip') ?></label>
			<div class="group-controls">
				<input type="checkbox" name="sendClientIp"<?= $config['sendClientIp'] ? ' checked="checked"' : '' ?> />
			</div>
		</div>

		<?php if (FreshRSS_Context::systemConf()->unsafe_autologin_enabled): ?>
			<strong>
				<font color="red"><?= _t('ext.form_captcha.unsafe_login_warning') ?></font>
			</strong>
		<?php endif ?>
	</template>

	<template class="captchaTmpl" id="turnstile">
		<div class="form-group">
			<div class="group-controls">
				<p class="help"><?= _i('help') ?> <?= _t('ext.form_captcha.help.turnstile') ?></p>
			</div>
		</div>
	</template>
	<template class="captchaTmpl" id="recaptcha-v2">
		<div class="form-group">
			<div class="group-controls">
				<p class="help"><?= _i('help') ?> <?= _t('ext.form_captcha.help.recaptcha') ?></p>
			</div>
		</div>
	</template>
	<template class="captchaTmpl" id="recaptcha-v3">
		<div class="form-group">
			<div class="group-controls">
				<p class="help"><?= _i('help') ?> <?= _t('ext.form_captcha.help.recaptcha') ?></p>
			</div>
		</div>
	</template>
	<template class="captchaTmpl" id="hcaptcha">
		<div class="form-group">
			<div class="group-controls">
				<p class="help"><?= _i('help') ?> <?= _t('ext.form_captcha.help.hcaptcha') ?></p>
			</div>
		</div>
	</template>

	<div id="providerConfig"></div>
	<noscript>
		<strong><?= _t('gen.js.should_be_activated') ?></strong>
	</noscript>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
			<button id="captchaReset" type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
			<button id="clearFields" class="btn btn-attention"><?= _t('ext.form_captcha.clear_fields') ?></button>
		</div>
	</div>
</form>
